/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package EmergingComputerWorld;

import java.sql.*;
import javax.swing.*;

/**
 *
 * @author Prashant
 */
public class Home extends javax.swing.JFrame {

   // int userid;

    /**
     * Creates new form Home
     */
    public Home() {
        initComponents();
        setLocationRelativeTo(null);
        //this.userid = Manager.userId;
        try {
            Class.forName("java.sql.Driver");
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/stockmanagement?&serverTimezone=UTC", "root", "");
            String sql;
            sql = "select * from shop where shopid=" + Manager.userId + ";";
            Statement st = con.createStatement();
            ResultSet rs = st.executeQuery(sql);
            rs.next();
            UserIdlabel.setText("UserID: " + Manager.userId);
            ShopnameLabel.setText(rs.getString("shop_name"));
            shopDetails.setText(rs.getString("shop_add"));
            contactDetails.setText("ContactNo: " + rs.getString("shopphone1")
                    + "," + rs.getString("shopphone2")
                    + "  EmailID: " + rs.getString("shopemail"));

        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e.getMessage());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        UserIdlabel = new javax.swing.JLabel();
        ShopnameLabel = new javax.swing.JLabel();
        LogOutButton = new javax.swing.JButton();
        shopDetails = new javax.swing.JLabel();
        contactDetails = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        optionPannel = new javax.swing.JPanel();
        CreateBillButton = new javax.swing.JButton();
        ListOfSupplierButton = new javax.swing.JButton();
        InventoryManagementButton = new javax.swing.JButton();
        ListOfCustomerButton = new javax.swing.JButton();

        setUndecorated(true);

        UserIdlabel.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        UserIdlabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/EmergingComputerWorld/guard.png"))); // NOI18N
        UserIdlabel.setText("userId");

        ShopnameLabel.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        ShopnameLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ShopnameLabel.setText("Emerging Computer World");
        ShopnameLabel.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        LogOutButton.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        LogOutButton.setForeground(new java.awt.Color(255, 255, 255));
        LogOutButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/EmergingComputerWorld/Button-Log-Off-icon.png"))); // NOI18N
        LogOutButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LogOutButtonActionPerformed(evt);
            }
        });

        shopDetails.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        shopDetails.setForeground(new java.awt.Color(255, 255, 255));
        shopDetails.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        shopDetails.setText("Shop Address");
        shopDetails.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        contactDetails.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        contactDetails.setForeground(new java.awt.Color(255, 255, 255));
        contactDetails.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        contactDetails.setText("Contact Details");
        contactDetails.setToolTipText("");
        contactDetails.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        contactDetails.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        optionPannel.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Options", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Tahoma", 1, 18))); // NOI18N

        CreateBillButton.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        CreateBillButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/EmergingComputerWorld/Create-New-icon.png"))); // NOI18N
        CreateBillButton.setText("Create Bill");
        CreateBillButton.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        CreateBillButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CreateBillButtonActionPerformed(evt);
            }
        });

        ListOfSupplierButton.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        ListOfSupplierButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/EmergingComputerWorld/User-Group-icon.png"))); // NOI18N
        ListOfSupplierButton.setText("List Of Suppliers");
        ListOfSupplierButton.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        ListOfSupplierButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ListOfSupplierButtonActionPerformed(evt);
            }
        });

        InventoryManagementButton.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        InventoryManagementButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/EmergingComputerWorld/Inventory-icon.png"))); // NOI18N
        InventoryManagementButton.setText("Inventory");
        InventoryManagementButton.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        InventoryManagementButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                InventoryManagementButtonActionPerformed(evt);
            }
        });

        ListOfCustomerButton.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        ListOfCustomerButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/EmergingComputerWorld/User-Group-icon (1).png"))); // NOI18N
        ListOfCustomerButton.setText("List Of Customers");
        ListOfCustomerButton.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        ListOfCustomerButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ListOfCustomerButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout optionPannelLayout = new javax.swing.GroupLayout(optionPannel);
        optionPannel.setLayout(optionPannelLayout);
        optionPannelLayout.setHorizontalGroup(
            optionPannelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(optionPannelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(optionPannelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(CreateBillButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(ListOfCustomerButton, javax.swing.GroupLayout.DEFAULT_SIZE, 276, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 121, Short.MAX_VALUE)
                .addGroup(optionPannelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(ListOfSupplierButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(InventoryManagementButton, javax.swing.GroupLayout.DEFAULT_SIZE, 275, Short.MAX_VALUE))
                .addContainerGap())
        );
        optionPannelLayout.setVerticalGroup(
            optionPannelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(optionPannelLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(optionPannelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CreateBillButton)
                    .addComponent(InventoryManagementButton, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 52, Short.MAX_VALUE)
                .addGroup(optionPannelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(ListOfSupplierButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(ListOfCustomerButton, javax.swing.GroupLayout.DEFAULT_SIZE, 73, Short.MAX_VALUE))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator1)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(contactDetails, javax.swing.GroupLayout.PREFERRED_SIZE, 430, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(shopDetails, javax.swing.GroupLayout.PREFERRED_SIZE, 430, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(95, 95, 95))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(UserIdlabel, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(ShopnameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 642, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(43, 43, 43)
                        .addComponent(LogOutButton)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(optionPannel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(103, 103, 103))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(LogOutButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(ShopnameLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(UserIdlabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 21, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(shopDetails, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(contactDetails, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31)
                .addComponent(optionPannel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(25, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void LogOutButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LogOutButtonActionPerformed
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(null, "You have successfully logged out");
        Manager.getInstance().loginFrame.setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_LogOutButtonActionPerformed

    private void ListOfCustomerButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ListOfCustomerButtonActionPerformed
        // TODO add your handling code here:
        new Custlist().setVisible(true);
        setVisible(false);

    }//GEN-LAST:event_ListOfCustomerButtonActionPerformed

    private void ListOfSupplierButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ListOfSupplierButtonActionPerformed
        // TODO add your handling code here:
        new Supplist().setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_ListOfSupplierButtonActionPerformed

    private void CreateBillButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CreateBillButtonActionPerformed
        // TODO add your handling code here:
        Manager.getInstance().billFrame.setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_CreateBillButtonActionPerformed

    private void InventoryManagementButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_InventoryManagementButtonActionPerformed
        // TODO add your handling code here:
        new Inventory().setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_InventoryManagementButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton CreateBillButton;
    private javax.swing.JButton InventoryManagementButton;
    private javax.swing.JButton ListOfCustomerButton;
    private javax.swing.JButton ListOfSupplierButton;
    private javax.swing.JButton LogOutButton;
    private javax.swing.JLabel ShopnameLabel;
    private javax.swing.JLabel UserIdlabel;
    private javax.swing.JLabel contactDetails;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JPanel optionPannel;
    private javax.swing.JLabel shopDetails;
    // End of variables declaration//GEN-END:variables

}
