package EmergingComputerWorld;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
import java.awt.AWTException;
import java.awt.Desktop;
import java.awt.HeadlessException;
import java.awt.Image;
import java.awt.SystemTray;
import java.awt.Toolkit;
import java.awt.TrayIcon;
import java.awt.TrayIcon.MessageType;
import java.io.File;
import java.io.IOException;
import java.sql.*;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.*;

/**
 *
 * @author Prashant Karna
 */
public class Login extends javax.swing.JFrame {

    /**
     * Creates new form NewJFrame
     */
    public Login() {
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        LoginPannel = new javax.swing.JPanel();
        nameLabel = new javax.swing.JLabel();
        ExitButton = new javax.swing.JButton();
        LoginButton = new javax.swing.JButton();
        LoginDetailsPannel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtUserId = new javax.swing.JTextField();
        txtPassword = new javax.swing.JPasswordField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        forgotPasswordLabel = new javax.swing.JLabel();
        RegisteButton = new javax.swing.JButton();
        ClearButton = new javax.swing.JButton();
        helpButton = new javax.swing.JButton();
        copyrightButton = new javax.swing.JButton();
        modeButton = new javax.swing.JToggleButton();

        setUndecorated(true);
        setResizable(false);

        nameLabel.setFont(new java.awt.Font("Segoe Script", 3, 36)); // NOI18N
        nameLabel.setForeground(java.awt.SystemColor.activeCaption);
        nameLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        nameLabel.setText("Emerging Computers");

        ExitButton.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        ExitButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/EmergingComputerWorld/Knob-Cancel-icon.png"))); // NOI18N
        ExitButton.setText("EXIT");
        ExitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ExitButtonActionPerformed(evt);
            }
        });

        LoginButton.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        LoginButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/EmergingComputerWorld/Apps-Computer-Login-icon.png"))); // NOI18N
        LoginButton.setText(" LOGIN ");
        LoginButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LoginButtonActionPerformed(evt);
            }
        });

        LoginDetailsPannel.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Enter Login Details", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Tahoma", 1, 14))); // NOI18N

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/EmergingComputerWorld/user.png"))); // NOI18N
        jLabel1.setText("User ID :");

        txtUserId.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtUserId.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        txtPassword.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtPassword.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/EmergingComputerWorld/Apps-Keys-icon.png"))); // NOI18N
        jLabel2.setText("Password :");

        jLabel3.setFont(new java.awt.Font("Arial Narrow", 2, 18)); // NOI18N
        jLabel3.setText("(Only Numeric ID allowed)");

        forgotPasswordLabel.setForeground(new java.awt.Color(51, 51, 255));
        forgotPasswordLabel.setText("Forgot Password");
        forgotPasswordLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                forgotPasswordLabelMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout LoginDetailsPannelLayout = new javax.swing.GroupLayout(LoginDetailsPannel);
        LoginDetailsPannel.setLayout(LoginDetailsPannelLayout);
        LoginDetailsPannelLayout.setHorizontalGroup(
            LoginDetailsPannelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, LoginDetailsPannelLayout.createSequentialGroup()
                .addGroup(LoginDetailsPannelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(LoginDetailsPannelLayout.createSequentialGroup()
                        .addGap(45, 45, 45)
                        .addComponent(jLabel2))
                    .addGroup(LoginDetailsPannelLayout.createSequentialGroup()
                        .addGap(59, 59, 59)
                        .addComponent(jLabel1))
                    .addGroup(LoginDetailsPannelLayout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(jLabel3)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(LoginDetailsPannelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtUserId, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 458, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, LoginDetailsPannelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(forgotPasswordLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 450, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        LoginDetailsPannelLayout.setVerticalGroup(
            LoginDetailsPannelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(LoginDetailsPannelLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(LoginDetailsPannelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtUserId, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(LoginDetailsPannelLayout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 54, Short.MAX_VALUE)
                .addGroup(LoginDetailsPannelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(18, 18, 18)
                .addComponent(forgotPasswordLabel)
                .addGap(95, 95, 95))
        );

        RegisteButton.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        RegisteButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/EmergingComputerWorld/signup-icon.png"))); // NOI18N
        RegisteButton.setText("Register");
        RegisteButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RegisteButtonActionPerformed(evt);
            }
        });

        ClearButton.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        ClearButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/EmergingComputerWorld/Actions-edit-clear-icon.png"))); // NOI18N
        ClearButton.setText("Clear");
        ClearButton.setPreferredSize(new java.awt.Dimension(179, 81));
        ClearButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ClearButtonActionPerformed(evt);
            }
        });

        helpButton.setBackground(new java.awt.Color(0, 255, 204));
        helpButton.setForeground(new java.awt.Color(0, 102, 102));
        helpButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/EmergingComputerWorld/Knob-Help-icon.png"))); // NOI18N
        helpButton.setBorder(new javax.swing.border.MatteBorder(null));
        helpButton.setBorderPainted(false);
        helpButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                helpButtonActionPerformed(evt);
            }
        });

        copyrightButton.setForeground(new java.awt.Color(0, 102, 102));
        copyrightButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/EmergingComputerWorld/Knob-Info-icon.png"))); // NOI18N
        copyrightButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                copyrightButtonActionPerformed(evt);
            }
        });

        modeButton.setForeground(java.awt.Color.gray);
        modeButton.setText("Invert Light/Dark Mode");
        modeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                modeButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout LoginPannelLayout = new javax.swing.GroupLayout(LoginPannel);
        LoginPannel.setLayout(LoginPannelLayout);
        LoginPannelLayout.setHorizontalGroup(
            LoginPannelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(LoginPannelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(LoginPannelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(LoginDetailsPannel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(LoginPannelLayout.createSequentialGroup()
                        .addComponent(RegisteButton)
                        .addGap(36, 36, 36)
                        .addComponent(nameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 472, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ExitButton, javax.swing.GroupLayout.DEFAULT_SIZE, 157, Short.MAX_VALUE))
                    .addGroup(LoginPannelLayout.createSequentialGroup()
                        .addComponent(helpButton)
                        .addGap(69, 69, 69)
                        .addComponent(LoginButton)
                        .addGap(63, 63, 63)
                        .addComponent(modeButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(ClearButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(22, 22, 22)
                        .addComponent(copyrightButton, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        LoginPannelLayout.setVerticalGroup(
            LoginPannelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(LoginPannelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(LoginPannelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(RegisteButton)
                    .addComponent(ExitButton, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(LoginDetailsPannel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(LoginPannelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(LoginPannelLayout.createSequentialGroup()
                        .addGroup(LoginPannelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(LoginPannelLayout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addGroup(LoginPannelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(ClearButton, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(LoginButton)))
                            .addGroup(LoginPannelLayout.createSequentialGroup()
                                .addGap(43, 43, 43)
                                .addComponent(copyrightButton, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(LoginPannelLayout.createSequentialGroup()
                                .addGap(43, 43, 43)
                                .addComponent(helpButton)))
                        .addGap(0, 16, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, LoginPannelLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(modeButton)))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(LoginPannel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
            .addComponent(LoginPannel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void ClearButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ClearButtonActionPerformed
        // TODO add your handling code here:
        txtUserId.setText("7890");
        txtPassword.setText("power");
    }//GEN-LAST:event_ClearButtonActionPerformed

    private void LoginButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LoginButtonActionPerformed
        // TODO add your handling code here:
        try {
            Class.forName("java.sql.Driver");
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/stockmanagement?&serverTimezone=UTC", "root", "");

            int sid;
            String pass, sql;
            if (txtUserId.getText().equals("")) {
                JOptionPane.showMessageDialog(this, "You can`t leave userID blank");
            } else {
                sid = Integer.parseInt(txtUserId.getText());
                Manager.userId = sid;
                sql = "select * from credentials where sid=" + sid + ";";
                Statement st = con.createStatement();
                ResultSet rs = st.executeQuery(sql);
                if (!rs.next()) {
                    JOptionPane.showMessageDialog(this, "Sorry userid is wrong");
                } else {
                    pass = new String(txtPassword.getPassword());
                    if (txtPassword.getPassword() == null) {
                        JOptionPane.showMessageDialog(this, "You can`t leave Password blank");
                    } else {
                        sql = "select * from credentials where pass='" + pass + "' and sid=" + sid + ";";
                        st = con.createStatement();
                        rs = st.executeQuery(sql);
                        if (!rs.next()) {
                            JOptionPane.showMessageDialog(this, "Sorry password is wrong");
                        } else {
                            //JOptionPane.showMessageDialog(null, "Your Login Was Successful");

                            SystemTray tray = SystemTray.getSystemTray();
                            Image image = Toolkit.getDefaultToolkit().createImage("C:\\Users\\Prashant\\Documents\\netbeans-project\\emerging-computer-world\\src\\resources\\EmergingComputerWorld\\Apps-Computer-Login-icon.png");
                            TrayIcon trayIcon = new TrayIcon(image, "Apps-Computer-Login-icon.png");
                            trayIcon.setToolTip("Login Message");
                            try {
                                tray.add(trayIcon);
                            } catch (AWTException ex) {
                                Logger.getLogger(Login.class.getName()).log(Level.SEVERE, null, ex);
                            }
                            trayIcon.displayMessage("Congratulations", "Successfully Logged In", MessageType.INFO);
                            Manager.getInstance().createFrames();
                            Manager.getInstance().homeFrame.setVisible(true);
                            txtUserId.setText("");
                            txtPassword.setText("");
                            this.setVisible(false);
                        }
                    }
                }
            }
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "ID must be NUMERIC");
        } catch (HeadlessException | ClassNotFoundException | SQLException e1) {
            JOptionPane.showMessageDialog(null, e1.getMessage());
        }
    }//GEN-LAST:event_LoginButtonActionPerformed

    private void ExitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ExitButtonActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_ExitButtonActionPerformed

    private void RegisteButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RegisteButtonActionPerformed
        // TODO add your handling code here:
        Manager.getInstance().registerFrame.setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_RegisteButtonActionPerformed

    private void helpButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_helpButtonActionPerformed
        try {
            File file = new File(getClass().getResource("/resources/EmergingComputerWorld/HelpDesk.pdf").getPath());
            if (!Desktop.isDesktopSupported()) {
                throw new IOException("Desktop is not supported");
            }
            Desktop desktop = Desktop.getDesktop();
            if (file.exists()) {
                desktop.open(file);
            }
        } catch (IOException ex) {
            Logger.getLogger(Login.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_helpButtonActionPerformed

    private void forgotPasswordLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_forgotPasswordLabelMouseClicked
        // TODO add your handling code here:
        new forgotPassword().setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_forgotPasswordLabelMouseClicked

    private void copyrightButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_copyrightButtonActionPerformed
        // TODO add your handling code here:
        try {
            File file = new File(getClass().getResource("/resources/EmergingComputerWorld/copyright.pdf").getPath());
            if (!Desktop.isDesktopSupported()) {
                throw new IOException("Desktop is not supported");
            }
            Desktop desktop = Desktop.getDesktop();
            if (file.exists()) {
                desktop.open(file);
            }
        } catch (IOException ex) {
            Logger.getLogger(Login.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_copyrightButtonActionPerformed

    private void modeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_modeButtonActionPerformed
        // TODO add your handling code here:
        if (modeButton.isSelected()) {
            if (PreferenceMan.getInstance().getPreference()) {
                PreferenceMan.getInstance().setPreference(false);

            } else {
                PreferenceMan.getInstance().setPreference(true);
            }
            JOptionPane.showMessageDialog(null, "Please Restart Manually");

        }
        System.exit(0);


    }//GEN-LAST:event_modeButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ClearButton;
    private javax.swing.JButton ExitButton;
    private javax.swing.JButton LoginButton;
    private javax.swing.JPanel LoginDetailsPannel;
    private javax.swing.JPanel LoginPannel;
    private javax.swing.JButton RegisteButton;
    private javax.swing.JButton copyrightButton;
    private javax.swing.JLabel forgotPasswordLabel;
    private javax.swing.JButton helpButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JToggleButton modeButton;
    private javax.swing.JLabel nameLabel;
    private javax.swing.JPasswordField txtPassword;
    private javax.swing.JTextField txtUserId;
    // End of variables declaration//GEN-END:variables
}
