/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package EmergingComputerWorld;

import javax.swing.*;
import java.sql.*;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author Prashant
 */
public class Receipt extends javax.swing.JFrame {

    Connection con;
    Statement st;
    PreparedStatement pst = null;
    ResultSet rs;
    
    
    
    int q[] = new int[8];
    float s1[] = new float[8];
    float amt[] = new float[8];
    float sum = 0.0f;
    int lastid;
    String name, add, email, contact1, contact2, billdate;
    
    public void getLastId()
    {
        try {
            Class.forName("java.sql.Driver");
            con = DriverManager.getConnection("jdbc:mysql://localhost:3306/stockmanagement?&serverTimezone=UTC", "root", "");
            String sql = "SELECT max(cust_id) from customer";
            st=con.createStatement();
            rs=st.executeQuery(sql);
            if(rs.next())
            {
              lastid = rs.getInt(1);
              lastid++;
              
            }
        } catch (ClassNotFoundException | SQLException ex) {
            Logger.getLogger(Receipt.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    /**
     * Creates new form Receipt
     *
     * @param a Array of Quantity
     * @param nameVar Name variable passed
     * @param addVar Address Variable
     * @param contact1Var contact1 variable passed
     * @param contact2Var contact2 variable passed
     * @param emailVar email variable passed
     * @param bdateVar Bill Date variable passed
     */
    public Receipt(int a[], String nameVar, String addVar, String contact1Var, String contact2Var, String emailVar, String bdateVar) {

        initComponents();
        setLocationRelativeTo(null);
        //userid = Manager.userId;
        System.arraycopy(a, 0, q, 0, 8);
        laptopQuantity.setText("" + q[0]);
        CAQuantity.setText("" + q[1]);
        CCQuantity.setText("" + q[2]);
        DSQuantity.setText("" + q[3]);
        printersQuantity.setText("" + q[4]);
        networkingQuantity.setText("" + q[5]);
        notebookQuantity.setText("" + q[6]);
        desktopsQuantity.setText("" + q[7]);
        name = nameVar;
        billDetailPannel.setText("Bill details for " + name + " is as follows: ");
        add = addVar;
        contact1 = contact1Var;
        contact2 = contact2Var;
        email = emailVar;
        billdate = bdateVar;
        try {
            Class.forName("java.sql.Driver");
            con = DriverManager.getConnection("jdbc:mysql://localhost:3306/stockmanagement?&serverTimezone=UTC", "root", "");
            
            String sql;
            sql = "select  hwstock.hid,hname,sp from hwlist,hwstock where hwstock.hid=hwlist.hid and shopid=" + Manager.userId + ";";
            st = con.createStatement();
            rs = st.executeQuery(sql);
            rs.next();
            for (int i = 0; i < 8; i++) {
                s1[i] = Float.parseFloat(rs.getString("sp"));
                rs.next();
            }
            
            laptopPpi.setText("" + s1[0]);
            accessoriesPpi.setText("" + s1[1]);
            componentsPpi.setText("" + s1[2]);
            storagePpi.setText("" + s1[3]);
            printersPpi.setText("" + s1[4]);
            networkingPpi.setText("" + s1[5]);
            notebookPpi.setText("" + s1[6]);
            desktopsPpi.setText("" + s1[7]);
            
            for (int i = 0; i < 8; i++) {
                amt[i] = q[i] * s1[i];
                sum += amt[i];
            }
            
            laptopAmount.setText("" + amt[0]);
            accessoriesAmount.setText("" + amt[1]);
            componentAmount.setText("" + amt[2]);
            drivesAmount.setText("" + amt[3]);
            printersAmount.setText("" + amt[4]);
            networkingAmount.setText("" + amt[5]);
            notebookAmount.setText("" + amt[6]);
            desktopsAmount.setText("" + amt[7]);
            totalJLabel.setText("Total Amount = " + sum);
        } catch (ClassNotFoundException | NumberFormatException | SQLException e) {
            JOptionPane.showMessageDialog(null, e.getMessage());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        InvoicePannel = new javax.swing.JPanel();
        invoiceLabel = new javax.swing.JLabel();
        billDetailPannel = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        Laptoplabel = new javax.swing.JLabel();
        CAlabel = new javax.swing.JLabel();
        CClabel = new javax.swing.JLabel();
        DSlabel = new javax.swing.JLabel();
        PrinterLabel = new javax.swing.JLabel();
        NetworkingLabel = new javax.swing.JLabel();
        NotebookLabel = new javax.swing.JLabel();
        DesktopLabel = new javax.swing.JLabel();
        laptopQuantity = new javax.swing.JLabel();
        CAQuantity = new javax.swing.JLabel();
        CCQuantity = new javax.swing.JLabel();
        DSQuantity = new javax.swing.JLabel();
        printersQuantity = new javax.swing.JLabel();
        networkingQuantity = new javax.swing.JLabel();
        notebookQuantity = new javax.swing.JLabel();
        desktopsQuantity = new javax.swing.JLabel();
        laptopPpi = new javax.swing.JLabel();
        accessoriesPpi = new javax.swing.JLabel();
        componentsPpi = new javax.swing.JLabel();
        storagePpi = new javax.swing.JLabel();
        printersPpi = new javax.swing.JLabel();
        networkingPpi = new javax.swing.JLabel();
        notebookPpi = new javax.swing.JLabel();
        desktopsPpi = new javax.swing.JLabel();
        laptopAmount = new javax.swing.JLabel();
        accessoriesAmount = new javax.swing.JLabel();
        componentAmount = new javax.swing.JLabel();
        drivesAmount = new javax.swing.JLabel();
        printersAmount = new javax.swing.JLabel();
        networkingAmount = new javax.swing.JLabel();
        notebookAmount = new javax.swing.JLabel();
        desktopsAmount = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        totalJLabel = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        CancelButton = new javax.swing.JButton();
        ConfirmButton = new javax.swing.JButton();

        setUndecorated(true);

        invoiceLabel.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        invoiceLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        invoiceLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/EmergingComputerWorld/invoice-icon.png"))); // NOI18N
        invoiceLabel.setText("Invoice");

        billDetailPannel.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        billDetailPannel.setText("Bill details for");

        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 22)); // NOI18N
        jLabel3.setText("Items");

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 22)); // NOI18N
        jLabel4.setText("Quantity");

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 22)); // NOI18N
        jLabel5.setText("Price per Item");

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 22)); // NOI18N
        jLabel6.setText("Amount");

        Laptoplabel.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        Laptoplabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/EmergingComputerWorld/laptop-icon.png"))); // NOI18N
        Laptoplabel.setText("Laptop");

        CAlabel.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        CAlabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/EmergingComputerWorld/Headphones-icon.png"))); // NOI18N
        CAlabel.setText("Computer Accessories");

        CClabel.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        CClabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/EmergingComputerWorld/Motherboard.png"))); // NOI18N
        CClabel.setText("Computer Components");

        DSlabel.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        DSlabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/EmergingComputerWorld/USBFlashCard_CardReader_Card.png"))); // NOI18N
        DSlabel.setText("Drives and Storages");

        PrinterLabel.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        PrinterLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/EmergingComputerWorld/Print-icon.png"))); // NOI18N
        PrinterLabel.setText("Printers");

        NetworkingLabel.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        NetworkingLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/EmergingComputerWorld/EthernetCable.png"))); // NOI18N
        NetworkingLabel.setText("Networking");

        NotebookLabel.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        NotebookLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/EmergingComputerWorld/PortableComputer.png"))); // NOI18N
        NotebookLabel.setText("Notebook");

        DesktopLabel.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        DesktopLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/EmergingComputerWorld/Computer.png"))); // NOI18N
        DesktopLabel.setText("Desktops");

        laptopQuantity.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        laptopQuantity.setText("Lap Quan");

        CAQuantity.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        CAQuantity.setText("CA Quan");

        CCQuantity.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        CCQuantity.setText("CC Quan");

        DSQuantity.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        DSQuantity.setText("DS Quan");

        printersQuantity.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        printersQuantity.setText("Printer Quan");

        networkingQuantity.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        networkingQuantity.setText("Networking Quan");

        notebookQuantity.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        notebookQuantity.setText("Notebook Quan");

        desktopsQuantity.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        desktopsQuantity.setText("Desktops Quan");

        laptopPpi.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        laptopPpi.setText("Laptop PPI");

        accessoriesPpi.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        accessoriesPpi.setText("CA PPI");

        componentsPpi.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        componentsPpi.setText("CC PPI");

        storagePpi.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        storagePpi.setText("DS PPI");

        printersPpi.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        printersPpi.setText("Printers PPI");

        networkingPpi.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        networkingPpi.setText("Networking PPI");

        notebookPpi.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        notebookPpi.setText("Notebook PPI");

        desktopsPpi.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        desktopsPpi.setText("Desktop PPI");

        laptopAmount.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        laptopAmount.setText("Lap Amount");

        accessoriesAmount.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        accessoriesAmount.setText("CA Amount");

        componentAmount.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        componentAmount.setText("CC Amount");

        drivesAmount.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        drivesAmount.setText("DS Amount");

        printersAmount.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        printersAmount.setText("Printers Amount");

        networkingAmount.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        networkingAmount.setText("Networking Amount");

        notebookAmount.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        notebookAmount.setText("Notebook Amount");

        desktopsAmount.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        desktopsAmount.setText("Desktops Amount");

        totalJLabel.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        totalJLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/EmergingComputerWorld/06-Wallet-icon.png"))); // NOI18N
        totalJLabel.setText("Total Amount");
        totalJLabel.setToolTipText("");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(CAlabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(Laptoplabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(CClabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(DSlabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(PrinterLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(NetworkingLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(NotebookLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(DesktopLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 44, Short.MAX_VALUE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(desktopsQuantity, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(notebookQuantity, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(CAQuantity)
                                    .addComponent(laptopQuantity)
                                    .addComponent(CCQuantity)
                                    .addComponent(printersQuantity, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(DSQuantity)
                                    .addComponent(networkingQuantity, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(120, 120, 120)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(notebookPpi, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 1, Short.MAX_VALUE)
                            .addComponent(networkingPpi, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 1, Short.MAX_VALUE)
                            .addComponent(printersPpi, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 1, Short.MAX_VALUE)
                            .addComponent(storagePpi, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(componentsPpi, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(accessoriesPpi, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(laptopPpi, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(desktopsPpi, javax.swing.GroupLayout.PREFERRED_SIZE, 1, Short.MAX_VALUE))
                        .addGap(151, 151, 151)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(accessoriesAmount)
                            .addComponent(componentAmount)
                            .addComponent(drivesAmount)
                            .addComponent(notebookAmount, javax.swing.GroupLayout.PREFERRED_SIZE, 1, Short.MAX_VALUE)
                            .addComponent(networkingAmount, javax.swing.GroupLayout.PREFERRED_SIZE, 1, Short.MAX_VALUE)
                            .addComponent(printersAmount, javax.swing.GroupLayout.PREFERRED_SIZE, 1, Short.MAX_VALUE)
                            .addComponent(laptopAmount, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(desktopsAmount, javax.swing.GroupLayout.PREFERRED_SIZE, 1, Short.MAX_VALUE))
                        .addGap(94, 94, 94))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel4)
                                .addGap(92, 92, 92)
                                .addComponent(jLabel5)
                                .addGap(54, 54, 54)
                                .addComponent(jLabel6)
                                .addGap(79, 79, 79))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 244, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(totalJLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 336, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(22, 22, 22))))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jSeparator2))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(2, 2, 2))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Laptoplabel)
                    .addComponent(laptopQuantity)
                    .addComponent(laptopPpi)
                    .addComponent(laptopAmount))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CAlabel)
                    .addComponent(CAQuantity)
                    .addComponent(accessoriesPpi)
                    .addComponent(accessoriesAmount))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CClabel)
                    .addComponent(CCQuantity)
                    .addComponent(componentsPpi)
                    .addComponent(componentAmount))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(DSlabel)
                    .addComponent(DSQuantity)
                    .addComponent(storagePpi)
                    .addComponent(drivesAmount))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(PrinterLabel)
                    .addComponent(printersQuantity)
                    .addComponent(printersPpi)
                    .addComponent(printersAmount))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(NetworkingLabel)
                    .addComponent(networkingQuantity)
                    .addComponent(networkingPpi)
                    .addComponent(networkingAmount))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(NotebookLabel)
                    .addComponent(notebookQuantity)
                    .addComponent(notebookPpi)
                    .addComponent(notebookAmount))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(DesktopLabel)
                    .addComponent(desktopsQuantity)
                    .addComponent(desktopsPpi)
                    .addComponent(desktopsAmount))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(totalJLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        CancelButton.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        CancelButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/EmergingComputerWorld/Knob-Cancel-icon.png"))); // NOI18N
        CancelButton.setText("Cancel Bill");
        CancelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CancelButtonActionPerformed(evt);
            }
        });

        ConfirmButton.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        ConfirmButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/EmergingComputerWorld/Knob-Valid-Green-icon.png"))); // NOI18N
        ConfirmButton.setText("Confirm  Bill");
        ConfirmButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ConfirmButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout InvoicePannelLayout = new javax.swing.GroupLayout(InvoicePannel);
        InvoicePannel.setLayout(InvoicePannelLayout);
        InvoicePannelLayout.setHorizontalGroup(
            InvoicePannelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, InvoicePannelLayout.createSequentialGroup()
                .addGap(130, 130, 130)
                .addComponent(ConfirmButton, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(CancelButton, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(237, 237, 237))
            .addGroup(InvoicePannelLayout.createSequentialGroup()
                .addGroup(InvoicePannelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(InvoicePannelLayout.createSequentialGroup()
                        .addGap(45, 45, 45)
                        .addComponent(billDetailPannel, javax.swing.GroupLayout.PREFERRED_SIZE, 486, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(InvoicePannelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(InvoicePannelLayout.createSequentialGroup()
                        .addGap(309, 309, 309)
                        .addComponent(invoiceLabel)))
                .addContainerGap(41, Short.MAX_VALUE))
        );
        InvoicePannelLayout.setVerticalGroup(
            InvoicePannelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(InvoicePannelLayout.createSequentialGroup()
                .addComponent(invoiceLabel)
                .addGap(4, 4, 4)
                .addComponent(billDetailPannel, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(InvoicePannelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(CancelButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(ConfirmButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(InvoicePannel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(InvoicePannel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ConfirmButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ConfirmButtonActionPerformed
        // TODO add your handling code here:
        int confirm = JOptionPane.showConfirmDialog(this, "Confirm Payment ?");
        switch (confirm) {
            case JOptionPane.YES_OPTION:
                try {
                Class.forName("java.sql.Driver");
               con = DriverManager.getConnection("jdbc:mysql://localhost:3306/stockmanagement?&serverTimezone=UTC", "root", "");
                String sql, sql1;
                sql = " insert into customer(cust_id,cust_name,cust_add,custphone1,custphone2,custemail,total,billdate,shopid) values('" + lastid + "','" + name + "','" + add + "','" + contact1 + "','" + contact1 + "','" + email + "'," + sum + ",'" + billdate + "'," + Manager.userId + ");";
               st = con.createStatement();
                st.executeUpdate(sql);
                for (int id = 311, i = 0; id <= 318 && i < 8; id++, i++) {
                    sql1 = "update hwstock set quantity=quantity-" + q[i] + " where shopid=" + Manager.userId + " and hid=" + id + ";";
                    Statement st1 = con.createStatement();
                    st1.executeUpdate(sql1);
                }
            } catch (ClassNotFoundException | SQLException e) {
                JOptionPane.showMessageDialog(null, e.getMessage());
            }
            JOptionPane.showMessageDialog(null, "Transaction Completed\nCustomer details added to database\n Returning to Home Screen");

            Manager.getInstance().homeFrame.setVisible(true);
            setVisible(false);
            break;
            case JOptionPane.NO_OPTION:
                JOptionPane.showMessageDialog(this, "Payment Due");
                break;
        }
    }//GEN-LAST:event_ConfirmButtonActionPerformed

    private void CancelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CancelButtonActionPerformed
        // TODO add your handling code here:
        int confirm = JOptionPane.showConfirmDialog(this, "Are you sure,you want to discard this bill ?");
        switch (confirm) {
            case JOptionPane.YES_OPTION:
                Manager.getInstance().homeFrame.setVisible(true);
                setVisible(false);
                break;
            case JOptionPane.NO_OPTION:
                JOptionPane.showMessageDialog(this, "Payment Due");
                break;
        }
    }//GEN-LAST:event_CancelButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel CAQuantity;
    private javax.swing.JLabel CAlabel;
    private javax.swing.JLabel CCQuantity;
    private javax.swing.JLabel CClabel;
    private javax.swing.JButton CancelButton;
    private javax.swing.JButton ConfirmButton;
    private javax.swing.JLabel DSQuantity;
    private javax.swing.JLabel DSlabel;
    private javax.swing.JLabel DesktopLabel;
    private javax.swing.JPanel InvoicePannel;
    private javax.swing.JLabel Laptoplabel;
    private javax.swing.JLabel NetworkingLabel;
    private javax.swing.JLabel NotebookLabel;
    private javax.swing.JLabel PrinterLabel;
    private javax.swing.JLabel accessoriesAmount;
    private javax.swing.JLabel accessoriesPpi;
    private javax.swing.JLabel billDetailPannel;
    private javax.swing.JLabel componentAmount;
    private javax.swing.JLabel componentsPpi;
    private javax.swing.JLabel desktopsAmount;
    private javax.swing.JLabel desktopsPpi;
    private javax.swing.JLabel desktopsQuantity;
    private javax.swing.JLabel drivesAmount;
    private javax.swing.JLabel invoiceLabel;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JLabel laptopAmount;
    private javax.swing.JLabel laptopPpi;
    private javax.swing.JLabel laptopQuantity;
    private javax.swing.JLabel networkingAmount;
    private javax.swing.JLabel networkingPpi;
    private javax.swing.JLabel networkingQuantity;
    private javax.swing.JLabel notebookAmount;
    private javax.swing.JLabel notebookPpi;
    private javax.swing.JLabel notebookQuantity;
    private javax.swing.JLabel printersAmount;
    private javax.swing.JLabel printersPpi;
    private javax.swing.JLabel printersQuantity;
    private javax.swing.JLabel storagePpi;
    private javax.swing.JLabel totalJLabel;
    // End of variables declaration//GEN-END:variables
}
