/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package EmergingComputerWorld;

import java.awt.Graphics;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.SwingUtilities;

/**
 *
 * @author Prashant
 */
public class Splash extends javax.swing.JFrame {

    private int i;

    /**
     * Creates new form Splash
     */
    public Splash() {
        initComponents();
        setLocationRelativeTo(null);
    }

    public void updateSplash() {
        setVisible(true);
        System.out.println("start");
        loadingBar.setValue(0);
        loadingBar.setStringPainted(true);

        // Runs outside of the Swing UI thread
        new Thread(() -> {
            for (i = 0; i <= 100; i++) {
                // Runs inside of the Swing UI thread
                SwingUtilities.invokeLater(() -> {
                    loadingBar.setValue(i);
                    if(i==100){
                        this.dispose();
                         Manager.getInstance().loginFrame.setVisible(true);
                    }
                });
                try {
                    java.lang.Thread.sleep(30);
                } catch (InterruptedException ex) {
                    Logger.getLogger(Splash.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        }).start();     
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    //  @SuppressWarnings("unchecked");
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        loadingBar = new javax.swing.JProgressBar();
        image = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setLocationByPlatform(true);
        setUndecorated(true);
        setResizable(false);
        setType(java.awt.Window.Type.POPUP);

        jPanel1.setBackground(new java.awt.Color(0, 153, 204));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        loadingBar.setFont(new java.awt.Font("Tahoma", 3, 11)); // NOI18N
        loadingBar.setForeground(new java.awt.Color(0, 153, 153));
        loadingBar.setAutoscrolls(true);
        jPanel1.add(loadingBar, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 480, 610, 30));

        image.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/EmergingComputerWorld/Screenshot(1).png"))); // NOI18N
        image.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel1.add(image, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -40, 620, 570));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 610, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 542, Short.MAX_VALUE)
        );

        setSize(new java.awt.Dimension(610, 542));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JLabel image;
    private javax.swing.JPanel jPanel1;
    public javax.swing.JProgressBar loadingBar;
    // End of variables declaration//GEN-END:variables
}
